version: '3.4'

services:
  web:
    image: ${DOCKER_REGISTRY-}web
    build:
      context: .
      dockerfile: Web/Dockerfile
    ports:
      - 5000:80
      - 5001:443
    depends_on:
      - canvasassignmentsync.db

  canvasassignmentsync.db:
    image: postgres:13.2
    container_name: canvasassignmentsync_db
    environment:
      - POSTGRES_DB=canvasassignmentsync
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432